#!/usr/bin/env python3
"""
Quick Setup Script for AutoPrint Service

This interactive script helps you configure AutoPrint Service quickly.
"""

import os
import sys

def clear_screen():
    os.system('cls' if os.name == 'nt' else 'clear')

def print_header():
    print("=" * 70)
    print(" " * 20 + "AutoPrint Service Setup")
    print("=" * 70)
    print()

def get_input(prompt, default=""):
    if default:
        user_input = input(f"{prompt} [{default}]: ").strip()
        return user_input if user_input else default
    else:
        while True:
            user_input = input(f"{prompt}: ").strip()
            if user_input:
                return user_input
            print("This field is required. Please try again.")

def get_yes_no(prompt, default=True):
    default_str = "Y/n" if default else "y/N"
    while True:
        response = input(f"{prompt} [{default_str}]: ").strip().lower()
        if not response:
            return default
        if response in ['y', 'yes']:
            return True
        elif response in ['n', 'no']:
            return False
        print("Please enter 'y' or 'n'")

def main():
    clear_screen()
    print_header()
    
    print("Welcome! This wizard will help you configure AutoPrint Service.\n")
    print("Press Ctrl+C at any time to cancel.\n")
    
    try:
        # Email Configuration
        print("=" * 70)
        print("EMAIL CONFIGURATION")
        print("=" * 70)
        print()
        
        imap_host = get_input("IMAP Server (e.g., imap.gmail.com)", "imap.gmail.com")
        imap_port = get_input("IMAP Port", "993")
        imap_ssl = get_yes_no("Use SSL connection?", True)
        imap_username = get_input("Email Address")
        imap_password = get_input("Email Password or App-Specific Password")
        mailbox = get_input("Mailbox to Monitor", "Inbox")
        
        print()
        
        # Print Configuration
        print("=" * 70)
        print("PRINT CONFIGURATION")
        print("=" * 70)
        print()
        
        subject_prefix = get_input("Email Subject Prefix (only emails with this will print)", "[PRINT]")
        auto_print = get_yes_no("Enable automatic printing? (No = manual print dialog)", True)
        poll_interval = get_input("Check for new emails every N seconds", "30")
        
        print()
        
        # Advanced Configuration
        print("=" * 70)
        print("ADVANCED CONFIGURATION")
        print("=" * 70)
        print()
        
        chrome_path = get_input("Chrome Path (leave blank for auto-detect)", "")
        delete_after_print = get_yes_no("Delete emails after successful print? (NOT RECOMMENDED)", False)
        
        if delete_after_print:
            print("\n⚠️  WARNING: Emails will be PERMANENTLY DELETED after printing!")
            confirm = get_yes_no("Are you absolutely sure?", False)
            delete_after_print = confirm
        
        print()
        
        # Generate Configuration
        print("=" * 70)
        print("GENERATING CONFIGURATION")
        print("=" * 70)
        print()
        
        config_content = f"""# AutoPrint Service Configuration
# Generated by setup wizard

# ==========================
# EMAIL CONFIGURATION
# ==========================

IMAP_HOST = "{imap_host}"
IMAP_PORT = {imap_port}
IMAP_USE_SSL = {imap_ssl}
IMAP_USERNAME = "{imap_username}"
IMAP_PASSWORD = "{imap_password}"

MAILBOX = "{mailbox}"

# ==========================
# PRINT CONFIGURATION
# ==========================

SUBJECT_PREFIX = "{subject_prefix}"
AUTO_PRINT_ENABLED = {auto_print}
POLL_INTERVAL_SECONDS = {poll_interval}

# ==========================
# ADVANCED CONFIGURATION
# ==========================

CHROME_PATH = "{chrome_path}"
DELETE_EMAIL_AFTER_PRINT = {delete_after_print}
CHROME_PRINT_WAIT_SECONDS = 8
TEMP_FILE_CLEANUP_HOURS = 6

DEBUG = False
LOG_FILE = "autoprint.log"
PRINTED_UIDS_FILE = "printed_uids.txt"
"""
        
        # Write to file
        config_file = "autoprint_config.py"
        with open(config_file, "w") as f:
            f.write(config_content)
        
        print(f"✓ Configuration saved to: {config_file}")
        print()
        print("=" * 70)
        print("NEXT STEPS")
        print("=" * 70)
        print()
        print("1. Review your configuration in 'autoprint_config.py'")
        print("2. Copy the configuration section to 'autoprint.py'")
        print("3. Run: python autoprint.py")
        print()
        print("For more help, see README.md or INSTALL.md")
        print()
        print("=" * 70)
        
    except KeyboardInterrupt:
        print("\n\nSetup cancelled by user.")
        sys.exit(0)
    except Exception as e:
        print(f"\n\nError during setup: {e}")
        sys.exit(1)

if __name__ == "__main__":
    main()
